branch-defaults:
  default:
    environment: null
    group_suffix: null
environment-defaults:
  dev-env:
    branch: null
    repository: null
global:
  application_name: edb
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
